# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JTN Design
email: jennifer@jtndesign.com
description: commercial and interior design for the baltimore area
url: "http://www.jtndesign.com/" # the base hostname & protocol for your site

host: localhost

include: ['_assets', '_pages']
exclude: [
  'Gruntfile.js',
  'package.json',
  'README.md',
  'to-do.md',
  'node_modules',
  'bower_components',
  '_assets/scss/*',
  '_assets/js/formConfirmation.js',
  '_assets/js/locations.js'
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"